# 错误处理和调试

## `try-catch`
ECMA-262 第三版引入了 `try-catch` 语句，作为 JavaScript 处理异常的一种标准方式。

```javascript
    try {
        // 可能会导致的错误的代码
        window.someNoneexistentFunction()
    } catch (error) {
        // 错误发生时怎么处理
        console.log(error.message)
    } finally {
        // 最后一定会执行的语句
    }
```

合理使用 `try-catch` 的时机是你不知道会不会有意无意地报错。如果知道自己代码可能报错，最好先检查参数类型等去处理掉。

## 错误类型

ECMA-262 定义了下列7种类型:

- Error 是基类型，其它错误类型都继承自该类型，因此，所有错误类型都共享了一组相同的属性。
- EvalError `EvalError` 类型的错误会在使用 `eval()` 函数发生异常时被抛出。
- RangeError `RangeError` 会在数值超出相应范围时触发。
- ReferenceError 找不到对象的时候会发生 `ReferenceError` 或者 `object expected`
- SyntaxError 把语法错误的 JavaScript 字符串传入 `eval()` 函数时，会就导致这个错误。
- TypeError 会在变量中保存着意外的类型时，或者访问不存在的方法时，都会导致这种错误。
- URIError 在使用 `encodeURI()` 或 `decodeURI()` 会导致 URIError 错误。

## throw 抛出错误

通过某种内置错误类型，可以更真实地模拟浏览器错误，每种错误类型的构造函数接收一个参数，即实际错误消息。

```javascript
    try{
        // 模拟抛出 ECMA-262 错误
        throw new Error('Something bad happened.')
        throw new SyntaxError('syntax Error')
        throw new TypeError('TypeError')
        throw new RangeError('Range Error')
        throw new EvalError('EvalError')
        throw new URIError('URIError')
        throw new ReferenceError('ReferenceError')
    } catch (error) {
        console.log(error.message)
    }

    // 自定义错误
    function CustomError(message) {
        this.name = 'CustomError'
        this.message = message
    }
    CustomError.prototype = new Error() // 继承 ECMA-262 错误基类
    throw new CustomError('My message') // 抛出自定义错误
```

关于何时抛出自定义模拟错误，应该在那些你能确切地知道如何处理的错误，去避免浏览器以默认方式处理他们。

在浏览器里面发生错误都会触发 `error` 事件,并执行这个事件处理程序。然后浏览器默认的机制发挥作用。

```javascript
    // 三个参数 错误消息， 错误所在，和 URL 行号。
    window.onerror = function(message, url, line) {
        console.log(message)
    }
```